[package]
name = "RustyIP"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
sha2 = "0.9.5"
hex = "0.4"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
pnet_datalink = "0.28"
openssl = { version = "0.10.54", features = ["vendored"] }
