[package]
name = "RustyIP"
version = "1.6.0"
edition = "2024"

[dependencies]
rand = "0.9"
sha2 = "0.10.9"
hex = "0.4"
reqwest = { version = "0.12.20", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
pnet_datalink = "0.35.0"
openssl = { version = "0.10.73", features = ["vendored"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[[bin]]
name = "RustyIP"
path = "src/main.rs"
