[package]
name = "RustyIP"
version = "0.1.0"
edition = "2021"
description = "A containerized dynamic DNS client."
license = "MIT"
repository = "https://github.com/richardsondev/rustyip"
homepage = "https://github.com/richardsondev/rustyip"
keywords = ["ddns", "dynamic-dns", "dns", "networking"]
categories = ["command-line-utilities", "network-programming"]

[dependencies]
rand = "0.9"
sha2 = "0.10.9"
hex = "0.4"
reqwest = { version = "0.12", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
pnet_datalink = "0.35.0"
openssl = { version = "0.10.73", features = ["vendored"] }
async-trait = "0.1"
url = "2.5.4"

[[bin]]
name = "RustyIP"
path = "src/main.rs"
