[package]
name = "RustyIP"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9"
sha2 = "0.10.9"
hex = "0.4"
reqwest = { version = "0.12.20", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
pnet_datalink = "0.35.0"
openssl = { version = "0.10.73", features = ["vendored"] }
url = ">=2.5.4"

[target.'cfg(windows)'.dependencies]
win32-ecoqos = "0.5.0"

[[bin]]
name = "RustyIP"
path = "src/main.rs"
