[package]
name = "RustyIP"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
sha2 = "0.10.8"
hex = "0.4"
reqwest = { version = "0.12", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
pnet_datalink = "0.35.0"
openssl = { version = "0.10.68", features = ["vendored"] }

[[bin]]
name = "RustyIP"
path = "src/main.rs"
