# Cross-compilation linkers
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = [
  # ARM64 size optimizations
  "-C", "opt-level=z",
  "-C", "link-arg=-s",
  "-C", "link-arg=-Wl,--gc-sections",
  "-C", "link-arg=-Wl,--strip-all",
]

[target.armv7-unknown-linux-gnueabihf] 
linker = "arm-linux-gnueabihf-gcc"
rustflags = [
  # ARM v7 size optimizations
  "-C", "opt-level=z",
  "-C", "link-arg=-s", 
  "-C", "link-arg=-Wl,--gc-sections",
  "-C", "link-arg=-Wl,--strip-all",
]

[target.arm-unknown-linux-gnueabi]
linker = "arm-linux-gnueabi-gcc"
rustflags = [
  # ARM v6 size optimizations
  "-C", "opt-level=z",
  "-C", "link-arg=-s",
  "-C", "link-arg=-Wl,--gc-sections", 
  "-C", "link-arg=-Wl,--strip-all",
]

[target.mips64-unknown-linux-gnuabi64]
linker = "mips64-linux-gnuabi64-gcc"
rustflags = [
  # MIPS64 size optimizations
  "-C", "opt-level=z",
  "-C", "link-arg=-s",
  "-C", "link-arg=-Wl,--gc-sections",
  "-C", "link-arg=-Wl,--strip-all",
]

# Additional targets for musl static builds
[target.x86_64-unknown-linux-musl]
rustflags = [
  # x86_64 musl optimizations
  "-C", "opt-level=z",
  "-C", "link-arg=-s",
  "-C", "link-arg=-Wl,--gc-sections",
  "-C", "link-arg=-Wl,--strip-all",
]

[target.i686-unknown-linux-musl]
linker = "gcc"
rustflags = [
  # i686 musl optimizations
  "-C", "opt-level=z",
  "-C", "link-arg=-s",
  "-C", "link-arg=-Wl,--gc-sections",
  "-C", "link-arg=-Wl,--strip-all",
]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"
rustflags = [
  # ARM64 musl optimizations
  "-C", "opt-level=z",
  "-C", "link-arg=-s",
  "-C", "link-arg=-Wl,--gc-sections",
  "-C", "link-arg=-Wl,--strip-all",
]

[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-gnueabihf-gcc"
rustflags = [
  # ARMv7 musl optimizations
  "-C", "opt-level=z",
  "-C", "link-arg=-s",
  "-C", "link-arg=-Wl,--gc-sections",
  "-C", "link-arg=-Wl,--strip-all",
]

[target.arm-unknown-linux-musleabi]
linker = "arm-linux-gnueabi-gcc"
rustflags = [
  # ARMv6 musl optimizations
  "-C", "opt-level=z",
  "-C", "link-arg=-s",
  "-C", "link-arg=-Wl,--gc-sections",
  "-C", "link-arg=-Wl,--strip-all",
]

# Windows targets
[target.x86_64-pc-windows-gnu]
rustflags = [
  # Windows x64 optimizations
  "-C", "opt-level=z",
  "-C", "link-arg=-s",
]

[target.i686-pc-windows-gnu]
rustflags = [
  # Windows x86 optimizations
  "-C", "opt-level=z", 
  "-C", "link-arg=-s",
]

# Build configuration
[build]
sparse-registry = true

[unstable]
build-std = ["std", "core", "alloc"]
